tests: test utils+config and refactor config

diff --git a/shelldoc b/shelldoc
--- a/shelldoc
+++ b/shelldoc
@@ -7,7 +7,8 @@ set -e
 readonly cmd="shelldoc"
 
 print_usage() {
-  usage_info=$(cat <<USAGE
+  usage_info=$(
+    cat <<USAGE
 \n
 Usage: ${cmd} [-c CONFIG_FILE][-d DESCRIPTION] [-h] [-m] [-r] [-t TITLE]
 
@@ -40,155 +41,182 @@ Options:
   \t Used as the name of the documentation when
   \t passed alongside -m or --multiple
   -r
-  --recurse\t Generate documenation from all shell
-  \t files in a project.
+  --recurse\t Scan all sub folders for comments.
 
   -t TITLE
   --title TITLE\t Sets the documenation's title.
  \n
 USAGE
-)
+  )
 
-echo -e "${usage_info}" | expand -t 30
+  echo -e "${usage_info}" | expand -t 30
 }
 
 # Handle errors
-trap "print_usage" ERR
-
+# trap "print_usage" ERR
 
 
 # config
 
-## @var {string=$config_configure} - Project configuration file. #
+## @var {file=$config_configure} - Project configuration file. #
+# Weird name but matches dynamically declared command line option
 config_configure="$(pwd)/shelldoc.conf"
 
 ## @var {string=$config_description} - Project/documentation description. #
-config_description="${cmd} Documentation"
+config_description="\`${cmd}\` Documentation"
 
-## @var {string=$config_exclude} - Comma-separated array of filename patterns to not parse. #
-declare -a config_exclude=()
+## @var {array=$config_exclude} - A comma-separated array of filename patterns to exclude from $config_include. #
+config_exclude=()
 
-## @var {string=$config_include} - Comma-separated array of filename patterns to parse. #
-declare -a config_include=(
-  "*.sh"
-  "*.bash"
-  "*.zsh"
-  "*.fish"
-)
+## @var {array=$config_include} - Comma-separated array of filename patterns to parse. #
+config_include=("*.sh" "*.bash")
 
-## @var {string=$config_multiple} - Generates multi-file documentation if true. #
+## @var {boolean=$config_multiple} - Generates multi-file documentation if true. #
 config_multiple=false
 
-## @var {string=$config_outfile} - Generated documentation file (or folder when using -m and -o options).
-config_outfile="$(basename "${PWD}")"
+## @var {string=$config_outfile} - Generated documentation file (or folder when using -m and -o options). #
+config_outfile="$(basename "${PROJECT_ROOT}")"
 
-## @var {string=$config_recurse} - Parse files in sub directories of included files.
+## @var {boolean=$config_recurse} - Parse files in sub directories of included files.
 config_recurse=false
 
 ## @var {string=$config_title} - The generated documentation's title.
 config_title="${cmd}"
 
-# Overwrite defaults with user's config file
-if [ -e "${config_configure}" ]; then
-  # Process each line
-  mapfile -t lines <"${config_configure}"
+## @var {boolean=$is_cmd_arg} #
+is_cmd_arg=false
 
-  for line in "${lines[@]}"; do
-    # Skip empty lines or comments
-    [[ -z "$line" || "$line" =~ ^# ]] && continue
+## @var {number=$shift_count=count} - Number of indexes to move when parsing command line args #
+shift_count=0
 
-    # Split the line into key and value
-    IFS='=' read -r key value <<<"$line"
+##
+# @arg {string} $1 - Config file field or command line option
+# @arg {string|boolean} $2 - Config file field or command line option argument
+#
+set_option() {
+  ## @var {boolean=$is_cmd_arg} #
+  is_cmd_arg=false
 
-    # Trim leading/trailing whitespace
-    key=$(echo "${key}" | xargs)
-    value=$(echo "${value}" | xargs)
+  if [[ "$1" =~ ^\- ]]; then
+    is_cmd_arg=true
+  fi
 
-    if [[ "${key}" == "include" || "${key}" == "exclude" ]]; then
-      # Strip all spaces
-      value="$(echo "${value}" | tr -d " ")"
-
-      # Convert to array and overwrite default
-      IFS="," read -r -a "config_${key}" <<<"${value}"
-      continue
-    fi
-
-    # Dynamically overwrite defaults
-    declare "config_${key}=${value}"
-  done
-fi
-
-args="${@}"
-
-# read arguments
-opts=$(
-  getopt -o "c:d:e:hi:mo:r:t" \
-    -l "configure:,description:,exclude:,help:,include:,multiple,outfile:,recurse,title:" \
-    --name "${cmd}" \
-    -- "$@"
-)
-
-# Parse arguments
-eval set -- "${opts}"
-
-# Overwrite default config and config file
-while [ $# -gt 0 ]; do
+  # Overwrite default config or config file configs
   case "${1}" in
+  ## @option %config_configure #
   -c | --configure)
     config_configure="${2}"
-    shift 2
+    shift_count=2
+    return 0
     ;;
 
-  -d | --description)
+  ## @option %config_description #
+  -d | --description | description)
     config_description="${2}"
-    shift 2
+    shift_count=2
+    return 0
     ;;
 
-  -e | --exclude)
+  ## @option %config_exclude #
+  -e | --exclude | exclude)
     exclude_patterns="$(echo "${2}" | tr -d " ")"
-    IFS="," read -r -a config_exclude <<<"${2}"
-    shift 2
+    IFS="," read -r -a patterns <<<"${2}"
+
+    config_exclude=(${patterns[@]})
+    shift_count=2
+    return 0
     ;;
 
+  ## @option - Prints help/usage information #
   -h | --help)
     print_usage
     exit 0
     ;;
 
-  -i | --include)
-    include_patterns="$(echo "${2}" | tr -d " ")"
-    IFS="," read -r -a config_include <<<"${2}"
-    shift 2
+  ## @todo Consider allowing multiple -i options to pass one pattern each. #
+  ## @option %config_include #
+  -i | --include | include)
+    patterns="$(echo "${2}" | tr -d " ")"
+    IFS="," read -r -a patterns <<<"${2}"
+    config_include=(${patterns[@]})
+    shift_count=2
+    return 0
     ;;
 
-  -m | --multiple)
+  ## @option %config_multiple #
+  -m | --multiple | multiple)
     config_multiple=true
-    shift
+    shift_count=1
+    return 0
     ;;
 
-  -o | --outfile)
+  ## @option %configure_outfile #
+  -o | --outfile | outfile)
     config_outfile="${2}"
-    shift 2
+    shift_count=2
+    return 0
     ;;
 
-  -r | --recurse)
+  ## @option %config_recurse #
+  -r | --recurse | recurse)
     config_recurse=true
-    shift
+    shift_count=1
+    return 0
     ;;
 
-  -t | --title)
+  -t | --title | title)
+    ## @option %config_title #
     config_title="${2}"
-    shift 2
+    shift_count=2
+    return 0
     ;;
 
   --)
-    shift
-    break
+    return 0
     ;;
 
   *)
-    break
+    [ "${is_cmd_arg}" == false ] && echo -e "${cmd}: Error\nUnknown configuration field '${1}' in ${config_configure}" && exit 1
     ;;
   esac
-  shift
-done
+}
+
+## Overwrites defaults with user's config file
+load_config_file() {
+  if [ -e "${config_configure}" ]; then
+    # Process each line
+    mapfile -t lines <"${config_configure}"
+
+    for line in "${lines[@]}"; do
+      # Skip empty lines or comments
+      [[ -z "$line" || "$line" =~ ^# ]] && continue
+
+      # Split the line into key and value
+      IFS='=' read -r key value <<<"$line"
+      # Trim leading/trailing whitespace
+      key=$(echo "${key}" | xargs)
+      value=$(echo "${value}" | xargs)
+
+      set_option "${key}" "${value}"
+    done
+  fi
+}
+
+# Parse arguments
+parse_cmd_args() {
+  # Define arguments
+  opts=$(
+    getopt -o "c:d:e:hi:mo:r:t" \
+      -l "configure:,description:,exclude:,help:,include:,multiple,outfile:,recurse,title:" \
+      --name "${cmd}" \
+      -- "$@"
+  )
+
+  eval set -- "${opts}"
+
+  # Overwrite default config and config file
+  while [ $# -gt 0 ]; do
+    set_option "${1}" "${2}"
+    $is_cmd_arg && shift $shift_count
+  done
+}
